baseURL = "https://k8sjp.github.io/kubefest-2020/"
title = "KubeFest Tokyo 2020"
theme = "kubefest"

enableEmoji = true
languageCode = "ja"
hasCJKLanguage = true

disableKinds = ["taxonomyTerm"]

[params]
  date = "2020/06/13(土)"
  venu = "Online"
  registerURL = "https://k8sjp.connpass.com/event/176105/"
  author = "KubeFest Tokyo 実行委員会"
  twitterName = "kcd_tokyo"
  description = "KubeFest Tokyo 2020 は Kubernetes を利用している人、これから導入したい人が新しいことを学んだり、ネットワーキングすることを狙いとして開催するワンデイのオンラインイベントです。"
  hashtag = "k8sjp"

[[params.tracks]]
  name = "Track1"
  youtube = "https://youtu.be/F-5TU7B40cA"
  hashtag = "k8sjp_t1"
[[params.tracks]]
  name = "Track2"
  youtube = "https://youtu.be/Tjdj7HuCUHA"
  hashtag = "k8sjp_t2"
[[params.tracks]]
  name = "Track3"
  youtube = "https://youtu.be/Tjdj7HuCUHA"
  hashtag = "k8sjp_t3"

[[menu.main]]
    url = ""
    name = "Home"
    weight = 100
[[menu.main]]
    url = "about"
    name = "About"
    weight = 200
[[menu.main]]
    url = "schedule"
    name = "Schedule"
    weight = 300
[[menu.main]]
    url = "sponsors"
    name = "Sponsors"
    weight = 400
