name = "Kubefest"
license = "Apache License 2.0"
licenselink = "https://github.com/k8sjp/kubefest-2020/blob/master/LICENSE"
description = "Conference Website for Kubernetes Fest Tokyo 2020"
homepage = "https://k8sjp.connpass.com/event/176105/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Kubernetes Meetup Tokyo Organizers"
  homepage = "https://k8sjp.connpass.com/event/176105/"
